### ISSUE TITLE
Unable to launch MEKA1.9.6 GUI

### ISSUE THREAD

**Issue by wghx** [Waikato/meka#76]
Hello, 
I have reviewed issue 69, but I am still unable to launch MEKA1.9.6 GUI in Win10 by double clicking the run.bat file. 
I have inserted the path to java at the top of the batch file as follows: "set /p path=[C:\Program Files\Java\jdk-18.0.1.1\bin1];%path%"
I have updated the JAVA_HOME environment variable. I uninstalled WEKA3.8.5 in case it was conflicting. 
When I launch MEKA I now get a command prompt window displaying various programs that use Java. 

Any help much appreciated.
Thank you.
Warren

**Comment by fracpete** [comment]
It says `bin1` in the path. Is that correct?

Also, try with Java 11 instead of 18.

**Comment by wghx** [comment]
Hi,
The path is actually bin, that's my typo error here. I have since downloaded 1.9.5 and that launces fine without adding path to Java at the top of the batch file. I then extracted 1.9.6 again from the zip, & this time did not add path to Java at the top of the batch file, and it still does not lauch; CMD screen appears for 2secs then disappears.

**Comment by wghx** [comment]
Error: Could not find or load main class meka.gui.guichooser.GUIChooser
Caused by: java.lang.ClassNotFoundException: meka.gui.guichooser.GUIChooser

**Comment by wghx** [comment]
I can't find the lib direcory in MEKA1.9.6, although I can see it in 1.9.5.

**Comment by fracpete** [comment]
Did you download the source zip file rather than the release one (`meka-release-1.9.6-bin.zip`)?

What was the link that you used for downloading? I tried both, the one hosted on [Github](https://github.com/Waikato/meka/releases/download/meka-1.9.6/meka-release-1.9.6-bin.zip) and the one on [Sourceforge.net](https://sourceforge.net/projects/meka/files/meka-1.9.6/meka-release-1.9.6-bin.zip/download) and they both work for me (under Linux).

This is the content of the `meka-release-1.9.6` directory after decompressing the release zip:
```
api/
data/
lib/
LICENSE.txt
run.bat
run.sh
src/
Tutorial.pdf
```

**Comment by wghx** [comment]
I had the source. I've now downloaded the release and it starts up fine under Win10. 
Is there anywhere that I can download other Multi-Target classifiers that output the numeric class?
Thank you.

**Comment by fracpete** [comment]
AFAIK, there are no classifiers in Meka that do regression.
